# 1.4.2 クラス

In [4]:
class Man:
    def __init__(self, name):
        self.name = name # インスタンス変数
        print("Initialized!")
    
    def hello(self):
        print("Hello " + self.name + "!")
    
    def goodbye(self):
        print("Good-bye " + self.name + "!")

In [5]:
m = Man("David")
m.hello()
m.goodbye()

Initialized!
Hello David!
Good-bye David!


# 1.5 Numpy

# 1.5.1 Numpyのインポート

In [8]:
import numpy as np

# 1.5.2 NumPy配列の作成

In [10]:
x = np.array([1.0, 2.0, 3.0])

In [11]:
print(x)

[1. 2. 3.]


In [13]:
print(type(x))

<class 'numpy.ndarray'>


# 1.5.3 NumPyの算術計算

要素ごとの計算（element-wiseな計算）

In [17]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])

x + y

array([3., 6., 9.])

In [18]:
x - y

array([-1., -2., -3.])

In [19]:
x * y

array([ 2.,  8., 18.])

In [20]:
x / y

array([0.5, 0.5, 0.5])

In [21]:
# ブロードキャストを利用した計算
x /2

array([0.5, 1. , 1.5])

# 1.5.4 NumPyのN次元配列

In [4]:
import numpy as np
A= np.array([[1, 2], [3, 4]])

In [5]:
A

array([[1, 2],
       [3, 4]])

In [6]:
A.shape

(2, 2)

In [7]:
A.dtype

dtype('int64')

In [10]:
B = np.array([[3, 5], [0, 6]])

In [12]:
A + B

array([[ 4,  7],
       [ 3, 10]])

In [13]:
A * B

array([[ 3, 10],
       [ 0, 24]])

In [15]:
A * 10

array([[10, 20],
       [30, 40]])

# 1.5.5 ブロードキャスト

形状の異なる配列に使います。2×2の行列にスカラーをかけて計算できるのはこのスカラーを2×2の行列にしているからです。

In [18]:
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])

In [19]:
A * B

array([[10, 40],
       [30, 80]])

# 1.5.6 要素へのアクセス

In [21]:
X = np.array([[51, 55], [14, 19], [0,4]])

In [22]:
print(X)

[[51 55]
 [14 19]
 [ 0  4]]


In [23]:
X[0]

array([51, 55])

In [24]:
X[0][1]

55

In [25]:
X[0][0]

51

In [26]:
for row in X:
    print(row)

[51 55]
[14 19]
[0 4]


In [28]:
X = X.flatten()

In [29]:
X

array([51, 55, 14, 19,  0,  4])

In [32]:
X[[0,2,4]] # インデックスが0,2,4を取得

array([51, 14,  0])

In [33]:
X > 15

array([ True,  True, False,  True, False, False])

In [35]:
X[X>15]

array([51, 55, 19])